import type { AgentCommand } from "@/lib/agent-command-catalogs";

// AGY 1.1.12 built-ins recovered from the installed binary and its bundled guide. Workspace and
// global skills/plugins add commands at runtime, so this is deliberately a partial fallback.
export const AGY: readonly AgentCommand[] = [
  { command: "/help", description: "Open AGY help", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/model", description: "Choose a model", takesArg: true, argHint: "[model]", common: true, dangerous: false },
  { command: "/resume", description: "Resume a conversation", takesArg: true, argHint: "[conversation]", common: true, dangerous: false },
  { command: "/tasks", description: "Show background tasks", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/permissions", description: "Review permission settings", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/skills", description: "Browse installed skills", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/agents", description: "Manage agents", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/mcp", description: "Manage MCP servers", takesArg: false, argHint: "", common: true, dangerous: false },
  { command: "/statusline", description: "Configure the status line", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/add-dir", description: "Add a working directory", takesArg: true, argHint: "<path>", common: false, dangerous: false },
  { command: "/artifact", description: "Manage artifacts", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/btw", description: "Ask a side question", takesArg: true, argHint: "<question>", common: false, dangerous: false },
  { command: "/changelog", description: "Show recent changes", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/clear", description: "Clear the current conversation", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/config", description: "Open configuration", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/context", description: "Inspect context usage", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/copy", description: "Copy the latest response", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/credits", description: "Show credits", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/diff", description: "Show working changes", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/effort", description: "Choose reasoning effort", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/feedback", description: "Send product feedback", takesArg: true, argHint: "[message]", common: false, dangerous: false },
  { command: "/fork", description: "Fork the current conversation", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/hooks", description: "Manage hooks", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/keybindings", description: "Review keybindings", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/logout", description: "Sign out", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/open", description: "Open a file or resource", takesArg: true, argHint: "<path>", common: false, dangerous: false },
  { command: "/rename", description: "Rename the conversation", takesArg: true, argHint: "<name>", common: false, dangerous: false },
  { command: "/rewind", description: "Rewind conversation state", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/search", description: "Search conversations or resources", takesArg: true, argHint: "<query>", common: false, dangerous: false },
  { command: "/title", description: "Set the conversation title", takesArg: true, argHint: "<title>", common: false, dangerous: false },
  { command: "/usage", description: "Show usage information", takesArg: false, argHint: "", common: false, dangerous: false },
  { command: "/exit", description: "Exit AGY", takesArg: false, argHint: "", common: false, dangerous: true },
  { command: "/quit", description: "Exit AGY", takesArg: false, argHint: "", common: false, dangerous: true },
];
