import type { AgentCommand } from "@/lib/agent-command-catalogs";

const command = (
  name: string,
  description: string,
  options: Partial<Pick<AgentCommand, "takesArg" | "argHint" | "common" | "dangerous">> = {},
): AgentCommand => ({
  command: `/${name}`,
  description,
  takesArg: options.takesArg ?? false,
  argHint: options.argHint ?? "",
  common: options.common ?? false,
  dangerous: options.dangerous ?? false,
});

// Senpi 2026.8.12-4 built-ins plus statically registered installed OMO/Senpi extensions. Runtime
// skills, prompt templates, MCP prompts, and conditional extensions remain outside this fallback.
export const OMO: readonly AgentCommand[] = [
  command("settings", "Open settings", { common: true }),
  command("ulw", "Run a task in ultrawork mode", {
    takesArg: true,
    argHint: "<task>",
    common: true,
  }),
  command("ulw-plan", "Create a decision-complete work plan", {
    takesArg: true,
    argHint: "<goal>",
    common: true,
  }),
  command("ulw-research", "Run an exhaustive research workflow", {
    takesArg: true,
    argHint: "<question>",
    common: true,
  }),
  command("model", "Choose a model", { takesArg: true, argHint: "[provider/model]", common: true }),
  command("favorite-models", "Manage favorite models", { common: true }),
  command("export", "Export the current session"),
  command("import", "Import a session", { takesArg: true, argHint: "<path>" }),
  command("share", "Share the current session"),
  command("copy", "Copy the latest response"),
  command("name", "Name the current session", { takesArg: true, argHint: "<name>" }),
  command("session", "Show session information"),
  command("changelog", "Show recent changes"),
  command("hotkeys", "Show keyboard shortcuts"),
  command("fork", "Fork the current session"),
  command("clone", "Clone the current session"),
  command("tree", "Browse the session tree"),
  command("trust", "Review workspace trust"),
  command("login", "Sign in to a provider", { takesArg: true, argHint: "[provider]" }),
  command("logout", "Sign out", { dangerous: true }),
  command("new", "Start a new session", { common: true, dangerous: true }),
  command("compact", "Compact conversation context", { takesArg: true, argHint: "[instructions]", common: true }),
  command("resume", "Resume a previous session", { takesArg: true, argHint: "[session]", common: true }),
  command("reload", "Reload extensions and resources"),
  command("quit", "Quit Senpi", { dangerous: true }),
  command("exit", "Quit Senpi", { dangerous: true }),
  command("btw", "Ask a side question", { takesArg: true, argHint: "<question>", common: true }),
  command("claude-account", "Manage Claude account selection"),
  command("diff", "Show working changes", { common: true }),
  command("doctor", "Diagnose the OMO installation", { common: true }),
  command("dream", "Run the memory dream workflow"),
  command("fallback", "Manage model fallback"),
  command("fast", "Toggle fast service tier"),
  command("files", "Browse files"),
  command("goal", "Manage the current goal", { common: true }),
  command("help", "Open Senpi help", { common: true }),
  command("history", "Search session history", { common: true }),
  command("hooks", "Inspect hooks"),
  command("init", "Initialize OMO project support"),
  command("ir", "Import a reproduction"),
  command("keybindings", "Review keybindings"),
  command("llama", "Open the Llama extension"),
  command("lookat", "Inspect an attached file", { takesArg: true, argHint: "<path>" }),
  command("mcp", "Manage MCP servers"),
  command("memfs", "Inspect memory filesystem state"),
  command("memory", "Manage persistent memory", { common: true }),
  command("memory-repository", "Open the memory repository"),
  command("omo-telemetry", "Review OMO telemetry"),
  command("palace", "Open the memory palace"),
  command("people", "Manage people records"),
  command("recompile", "Recompile OMO configuration"),
  command("reflect", "Run memory reflection"),
  command("reload-rules", "Reload active rules"),
  command("remember", "Save a durable memory", { takesArg: true, argHint: "<note>" }),
  command("rules", "Inspect active rules"),
  command("search", "Search OMO memory", { takesArg: true, argHint: "<query>", common: true }),
  command("sleeptime", "Configure sleep-time behavior"),
  command("task-kill", "Stop a background task", { takesArg: true, argHint: "<task>", dangerous: true }),
  command("tasks", "Show background tasks", { common: true }),
  command("todo", "Show or manage the task list", { common: true }),
  command("ttsr", "Control text-to-speech rendering"),
  command("tui", "Inspect TUI diagnostics"),
  command("websearch", "Search the web", { takesArg: true, argHint: "<query>", common: true }),
];
